baseurl = "/"
languageCode = "en-us"
title = "Anton Popov"
theme = "hugo-theme-novela"
publishDir = "docs"
relativeurls = true
rssFullText = true

pygmentsstyle = 'monokai'
paginate= 6
enableEmoji = true
enableRobotsTXT = true

[social]
  youtube= "https://www.youtube.com/c/AntonPopov/videos"
  instagram= "https://www.instagram.com/basicbb_com/"

[taxonomies]
  author = "authors"
