name: Hugo Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify

    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './docs'

    - name: Commit changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Automated snapshot

